[providers.age]
type = "age"
recipients = [
    "age1qcztzyvkp4yatuldq4k50rlj9c2z3hfymd9x0lkaxrfn5tr7dchs236n8g",
    "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKqGgvTCOAILQD/O1/yTh9K4pfTBFE+rUsPYshv1iuJU pedro@pepicrft.me",
]

[secrets.CLOUDFLARE_ACCOUNT_ID]
provider = "age"
value = "YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPZkF1K05EcGZ0VEN0a0Jhd29ORzhyT2pIamV0SmVFRzVpYXR2SFFNVHowCmc0Ri9oaTNOZkFHNWhJMVhxVkJSR21MeGdzVU5lYmw1Q09JOTFsNnd2RTQKLT4gc3NoLWVkMjU1MTkgOG9SN1VnIGZRMGZQR1pPNk1pTmVqLzZBd1FEeCt1RmlxSEsyKzBTME5ka1BnL2kxUVkKT1dFclJYN1ZWL21KQ0lqUzA3YWkxSy9JMkpEWkhGbXhLSDlzMllQOWZiTQotLS0gaTZ4V3RaL3A1bUhLU2dxYUJUS2ZEcTdud3ZWTE9jd0lCYmF6MTBuU0FXcwokK+MnGD/ViRthBDBN20ns5rIWM9mn2MBiyoBSoD41JUcNJYxwFN07tW7Nt7wioIcSVUVnQBXdk3DdK1UJVF8A"

[secrets.CLOUDFLARE_TOKEN]
provider = "age"
value = "YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsejhMeDRpRWVqZ0NpYWRhRjhiUXFDUlAwbEZDbGU4L0lmMWRkbEU5cUFzCnlJb3hIVnVSZG56ZHQwdFZiaDNEeERndmJRWHoxUlRIY3F5V2JNdWxkc1UKLT4gc3NoLWVkMjU1MTkgOG9SN1VnIDRjckUwNnZoeTdYUW9ZcDRiK2Z1VjhJcWgxSkFqTHBEaWwxZmYwSnI0VUEKdkV4aFI4R210TmhkOWV3Ri9PVUFYaG43R00vc3UxNlQ3VFJ5aXBLdVZDNAotLS0gb3dlaytNTW1kQldXajFybmRnaW5pOUh1Ry82VjgydTlLeGRQajV0Q0k4awqXRx/3asLy4WLFidTTZ3NGv67gxucj4QkNCwW4p6P7Jp+om6uPmdbszfISwfEoCLdW5K97Shl2Zqb3B6f8dW0HImLYAE9IfgQ="
