default_provider = "age"

[providers.age]
type = "age"
recipients = ["age1qcztzyvkp4yatuldq4k50rlj9c2z3hfymd9x0lkaxrfn5tr7dchs236n8g",
"ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKqGgvTCOAILQD/O1/yTh9K4pfTBFE+rUsPYshv1iuJU pedro@pepicrft.me"]
