#!/usr/bin/env -S fabrik run node
//FABRIK output "output.json"

const fs = require('fs');

console.log('Hello from simple Node script!');

const data = {
  message: 'Generated by Fabrik',
  timestamp: new Date().toISOString(),
  nodeVersion: process.version
};

fs.writeFileSync('output.json', JSON.stringify(data, null, 2));
console.log('Output written to output.json');
